Update spark-shell

diff --git a/API/spark-shell b/API/spark-shell
--- a/API/spark-shell
+++ b/API/spark-shell
@@ -1,61 +1,194 @@
-odate=$1
-country=$2
-timestamp=`date '+%H%M%S'`
-env=prod
+#!/bin/ksh
 
-log_file=${OCIR_HOME}/hdpcf/bin/MyUseCase/logs/Trade_Volume_${country}_${odate}_${timestamp}.log
-config_path=${OCIR_HOME}/hdpcf/bin/MyUseCase/scripts
-cat /dev/null > $log_file
+function errorHandler
+{
 
-
-#------------------ Loading connection.conf file ------------------------#
-. $config_path/MYUSECASE_PROPERTIES.txt
-. $config_path/connection.conf
-
-
-if [ $? -ne 0 ]
+if [ $# -lt 2 ]
 then
-	echo "$(date +%Y_%m_%d~%H:%M:%S) Error : Loading connection.conf file. So Quitting the job..." >> $log_file
-	exit 1
-	else
-	echo "$(date +%Y_%m_%d~%H:%M:%S) Info : Loaded connection.conf file  successfully..." >> $log_file
+        writeLog "ERROR : " "USAGE: errorHandler <retrurn_code> <error_msg> <success_msg>"
 fi
 
-num_executors="5"
-executor_cores="5"
-executor_memory="10G"
-driver_mem="12G"
-driver_crs="5"
+returnValue=$1
+errorValue=$2
+successValue=$3
 
-if [[ $env = 'dev' ]]; then
-queue="sgz1-ocirapp-haas_dev"
-elif [[ $env = 'sit' ]]; then
-queue="sgz1-ocirapp-haas_sit"
-else
-queue="sgz1-ocir_global_all_edmp_batchuser_fullaccess"
+if [ $# -eq 2 ]
+then
+        if [ ${returnValue} -ne 0 ]
+        then
+                writeLog "ERROR : " "${errorValue} Exiting with value ${returnValue}!!!"
+                exit ${returnValue}
+        fi
 fi
 
-#------------------ Loading Runtime parameters ------------------------#
-COUNTRY=`echo $COUNTRY | tr '[:lower:]' '[:upper:]'`
-odate=`date --date "${odate}-1 days" +'%Y%m%d'`
-o_date=`echo "$odate" | awk '{ print substr($0,1,4)"_"substr($0,5,2)"_"substr($0,7,2) }'`  #2019_06_15  
-o_date_otp=`echo "$odate" | awk '{ print substr($0,1,4)"-"substr($0,5,2)"-"substr($0,7,2) }'`  #2019-06-15 
-ccy_date=`echo "$odate" | awk '{ print substr($0,7,2)"/"substr($0,5,2)"/"substr($0,3,2) }'`  #2019-06-15 
-
-
-
-query2="INSERT OVERWRITE TABLE t3_ocir_open.ocir_DTP_TRADE_VOLUME_dremio partition(process_date,Data_src,source_country_code) select * from t3_ocir_open.ocir_DTP_TRADE_VOLUME where PROCESS_DATE='${o_date_otp}' and DATA_SRC='DTP' and SOURCE_COUNTRY_CODE='MY'"
-
-export SPARK_MAJOR_VERSION=2
-
-echo "spark-shell --master yarn --name 'Trade Volume Load2' --num-executors ${num_executors} --executor-cores ${executor_cores} --executor-memory ${executor_memory} --driver-memory ${driver_mem} --driver-cores ${driver_crs} --queue ${queue}  -i $config_path/ocir_query_execute.scala --conf spark.driver.args='${query2}'"
-
-spark-shell --master yarn --name "Trade Volume Load2" --num-executors ${num_executors} --executor-cores ${executor_cores} --executor-memory ${executor_memory} --driver-memory ${driver_mem} --driver-cores ${driver_crs} --queue ${queue}  -i $config_path/ocir_query_execute.scala --conf spark.driver.args="${query2}" >> $log_file 2>&1 
-
-if [ $? -ne 0 ]
-      then
-        echo "$(date +%Y_%m_%d~%H:%M:%S) Error : Loading ocir_DTP_TRADE_VOLUME_dremio is not successful, so exiting" >> $log_file 2>&1
-	exit 1
- 	else
-        echo "$(date +%Y_%m_%d~%H:%M:%S) Info : Loading ocir_DTP_TRADE_VOLUME_dremio succeeded" >> $log_file
+if [ $# -eq 3 ]
+then
+        if [ ${returnValue} -ne 0 ]
+        then
+                writeLog "ERROR : " "${errorValue} Exiting with value ${returnValue}!!!"
+                exit ${returnValue}
+		else
+				writeLog "SUCCESS : " "${successValue} Exiting with value ${returnValue}!!!"
+        fi
 fi
+
+}
+
+function writeLog
+{
+type=$1
+msg=$2
+timestamp=`date '+%Y-%m-%d %H:%M:%S'`
+
+echo "${timestamp}:[${type}] ${msg}" >> ${log_file}
+}
+
+#MAIN
+#INPUT CHECK
+#============================================================================================================================
+if [ $# -ne 5 ]
+then
+        errorHandler 1 "Script Usage: viewCreation.sh <TableListFile> <SourceDatabase> <DestinationDataBase> <env> <country>"
+fi
+
+#Assigning INPUT
+#============================================================================================================================
+table_list_file=$1
+source_database=$2
+destination_dataBase=$3
+env=$4
+country=$5
+
+DATE=`date +%Y-%m-%d`
+timestamp=`date +%Y%m%d_%H%M%S`
+
+#Environment Path
+log_path=${HOME}/work/report/logs
+file_path=${HOME}/work/report
+archive_path=${HOME}/work/report
+
+
+# Archive old files
+
+mv ${file_path}/drop*${table_list_file}* ${archive_path}/
+mv ${file_path}/column*${table_list_file}* ${archive_path}/
+mv ${file_path}/*${table_list_file}*.hql ${archive_path}/
+
+log_file=${log_path}/view_creation_${table_list_file}_${timestamp}.log
+hql_file=viewCreation_${table_list_file}_${timestamp}.hql
+column_list=column_list_${table_list_file}
+column_result=column_result_${table_list_file}
+drop_view_list=drop_view_${table_list_file}
+drop_masked_view_list=drop_masked_view_${table_list_file}
+mask_file=${table_list_file}_maskfile
+hql_mask_file=maskviewCreation_${table_list_file}_${timestamp}.hql
+
+#echo ${parameters} > ${file_path}/${hql_file}
+> ${column_list}
+> ${file_path}/${hql_file}
+> ${file_path}/${drop_view_list}
+> ${file_path}/${hql_mask_file}
+> ${log_file}
+
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "INFO : " "Preparing query to fetch column list from the sources"
+
+#remove when running with beeline
+echo "set hive.cli.print.header=true;" >> ${file_path}/${column_list}
+while IFS='' read -r line || [[ -n "$line" ]]; do
+	echo "drop view if exists $destination_dataBase.${line}_full_vw;" >> ${file_path}/${drop_view_list}
+	echo "drop view if exists $destination_dataBase.${line}_masked_vw;" >> ${file_path}/${drop_masked_view_list}
+	echo "select * from ${source_database}.$line limit 0;" >> ${file_path}/${column_list}
+done < ${file_path}/${table_list_file}
+
+
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "INFO : " "Running query to drop already existing full views"
+
+#${BEELINE_CONN} --outputformat=tsv2 -f ${file_path}/${drop_view_list} 2>> ${log_file}
+hive -f ${file_path}/${drop_view_list} 2>> ${log_file}
+#hive -f ${file_path}/${drop_view_list} 2>> ${log_file}
+
+hiveStatus=$?
+errorHandler ${hiveStatus} "There is an issue while dropping existing views" "Dropping existing view from $destination_dataBase completed successfully" 
+
+
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "INFO : " "Running query to fetch column list from the sources"
+
+#${BEELINE_CONN} --outputformat=tsv2 -f ${file_path}/${column_list} > ${file_path}/${column_result} 2>> ${log_file}
+hive -f ${file_path}/${column_list} > ${file_path}/${column_result} 2>> ${log_file}
+hiveStatus=$?
+errorHandler ${hiveStatus} "There is an issue while fetching column from ${source_database}" "Fetching column from ${source_database} database complete successfully"
+
+chmod 775 ${file_path}/*
+sed -i '$d' ${file_path}/${column_result}
+sed -i 's/[\t]/,/g' ${file_path}/${column_result}
+
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "INFO : " "Preparing query to create full views"
+
+while IFS='' read -r line || [[ -n "$line" ]]; do
+	#echo $line > $CAL_HOME_PK/Temp/test.txt
+	tableName=`echo $line | cut -d. -f1`
+	
+	echo "create view if not exists ${destination_dataBase}.${tableName}_full_vw as select ${line} from ${source_database}.${tableName};" >> ${file_path}/${hql_file}
+done < ${file_path}/${column_result}
+
+#Running query to create full views
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "INFO : " "Running query to create full views"
+
+#${BEELINE_CONN} --outputformat=tsv2 -f ${file_path}/${hql_file} 2>> ${log_file}
+hive -f ${file_path}/${hql_file} 2>> ${log_file}
+hiveStatus=$?
+errorHandler ${hiveStatus} "There is an issue while creating full views" "Full view creation completed successfully"
+
+
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "INFO : " "Running query to drop already existing masked views"
+
+#${BEELINE_CONN} --outputformat=tsv2 -f ${file_path}/${drop_masked_view_list} 2>> ${log_file}
+hive -f ${file_path}/${drop_masked_view_list} 2>> ${log_file}
+
+hiveStatus=$?
+errorHandler ${hiveStatus} "There is an issue while dropping existing views" "Dropping existing view from $destination_dataBase completed successfully" 
+
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "INFO : " "Preparing query to create masked views"
+
+cp ${file_path}/${hql_file} ${file_path}/${hql_mask_file}
+sed -i "s/_full_vw as select/_masked_vw as select/g" ${file_path}/${hql_mask_file}
+while IFS='' read -r line || [[ -n "$line" ]]; do
+
+	remainder=${line}
+	#database name
+	table_name="${remainder%%.*}"; remainder="${remainder#*.}"
+	#table name
+	column_name="${remainder%%.*}"; 
+	
+	sed -i "s/${line}/'XXXXXXXXXX' as ${column_name}/g" ${file_path}/${hql_mask_file}
+	
+done < ${file_path}/${mask_file}
+
+#Fetching table list
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "INFO : " "Running query to create masked views"
+
+#${BEELINE_CONN} --outputformat=tsv2 -f ${file_path}/${hql_mask_file} 2>> ${log_file}
+hive -f ${file_path}/${hql_mask_file} 2>> ${log_file}
+
+hiveStatus=$?
+errorHandler ${hiveStatus} "There is an issue while creating masked views" "Masked view creation completed successfully"
+
+writeLog " " " "
+writeLog "==============================================================================" 
+writeLog "SUCCESS : " "JOB to create view completed successfully"
